FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5278

ENV ASPNETCORE_URLS=http://+:5278

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["TranslatorService/TranslatorService.csproj", "./"]
RUN dotnet restore "TranslatorService.csproj"
COPY ../TranslatorService .
WORKDIR "/src/."
RUN dotnet build "TranslatorService.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "TranslatorService.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TranslatorService.dll"]
