# Use a Node.js base image
FROM node:lts-alpine

# Install a simple HTTP server to serve static content
RUN npm install -g http-server

# Set the working directory inside the container
WORKDIR /var/www/vue

# Копируем package.json и lock-файл
COPY /vue/package*.json ./

# Устанавливаем зависимости
RUN npm install

# Expose the port where the application will run
EXPOSE 8080

CMD ["npm", "run", "serve"]